---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_company_details(load_company_details)
	rewrite_constitution(rewrite_constitution)
	section_llm(section_llm)
	validation_agent(validation_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_company_details;
	load_company_details --> rewrite_constitution;
	rewrite_constitution --> section_llm;
	section_llm --> validation_agent;
	validation_agent -. &nbsp;end&nbsp; .-> __end__;
	validation_agent -. &nbsp;retry&nbsp; .-> section_llm;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
